name: Publish fhevm-tfhe-cli

on:
  release:
    types: [published]

env:
  DOCKER_IMAGE: ghcr.io/zama-ai/fhevm-tfhe-cli

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:

      - name: Check out fhevm-tfhe-cli
        uses: actions/checkout@v3
        with:
          repository: zama-ai/fhevm-tfhe-cli
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker tag
        run: |
          echo ${{ github.event.release.tag_name }}
      - name: Check OS
        run: |
          lscpu
          uname -r
          lsb_release -a

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.event.release.tag_name }},${{ env.DOCKER_IMAGE }}:latest
          labels: fhevm-tfhe-cli
